[tool.poetry]
name = "data-preprocessor"
version = "0.1.0"
description = "Configurable tools to easily preprocess your data for data-science and machine learning."
authors = ["Marco Gancitano <marco.gancitano97@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
